### ISSUE TITLE
AssertionError: track_path does not exist: /dev_ws/install/tracking/lib/tracking/data/map_data/traj_ltpl_cl_LVMS_GPS.csv

### ISSUE THREAD

**Issue by KaiMJ** [TUMFTM/FusionTracking#1]
Steps taken:
1. downloaded tracking data
2. Moved tracking_input under data
3. moved logs to tracking/tracking
4. run docker run tracking:0.0.1

[INFO] [launch]: All log files can be found below /root/.ros/log/2022-12-17-08-05-57-735074-0413cc0aa91c-1
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [tracking_node-1]: process started with pid [47]
[tracking_node-1] Traceback (most recent call last):
[tracking_node-1]   File "/dev_ws/install/tracking/lib/tracking/tracking_node", line 33, in <module>
[tracking_node-1]     sys.exit(load_entry_point('tracking==0.0.0', 'console_scripts', 'tracking_node')())
[tracking_node-1]   File "/dev_ws/install/tracking/lib/python3.8/site-packages/tracking/tracking_node.py", line 153, in main
[tracking_node-1]     tracking_node = TrackingNode()
[tracking_node-1]   File "/dev_ws/install/tracking/lib/python3.8/site-packages/tracking/tracking_node.py", line 23, in __init__
[tracking_node-1]     super().__init__(path_dict=PATH_DICT)
[tracking_node-1]   File "/dev_ws/install/tracking/lib/tracking/utils/ros2_interface.py", line 109, in __init__
[tracking_node-1]     self.get_params_from_config(path_dict=path_dict)
[tracking_node-1]   File "/dev_ws/install/tracking/lib/tracking/utils/ros2_interface.py", line 287, in get_params_from_config
[tracking_node-1]     _ = get_map_data(
[tracking_node-1]   File "/dev_ws/install/tracking/lib/tracking/utils/map_utils.py", line 115, in get_map_data
[tracking_node-1]     check_path_exist(main_class=main_class, key_str="track_path")
[tracking_node-1]   File "/dev_ws/install/tracking/lib/tracking/utils/map_utils.py", line 145, in check_path_exist
[tracking_node-1]     assert os.path.exists(main_class.params[key_str]), "{} does not exist: {}".format(
[tracking_node-1] AssertionError: track_path does not exist: /dev_ws/install/tracking/lib/tracking/data/map_data/traj_ltpl_cl_LVMS_GPS.csv
[ERROR] [tracking_node-1]: process has died [pid 47, exit code 1, cmd '/dev_ws/install/tracking/lib/tracking/tracking_node --ros-args --ros-args -r __node:=TRACKING -r __ns:=/ --params-file /tmp/launch_params_m6b06053'].

**Comment by phkarle** [comment]
Thanks for the hint. I just fixed it: the map files (.csv) were ignored by .gitignore.
Best regards, Phillip
